--
-- Name: favorite_rooms; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.favorite_rooms (
    added_at timestamp(6) without time zone,
    id bigint NOT NULL,
    room_id bigint,
    user_id bigint
);


ALTER TABLE public.favorite_rooms OWNER TO postgres;

--
-- Name: favorite_rooms_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.favorite_rooms ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.favorite_rooms_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: profiles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.profiles (
    date_of_birth date,
    id bigint NOT NULL,
    user_id bigint,
    bio character varying(255),
    gender character varying(255),
    CONSTRAINT profiles_gender_check CHECK (((gender)::text = ANY ((ARRAY['MALE'::character varying, 'FEMALE'::character varying])::text[])))
);


ALTER TABLE public.profiles OWNER TO postgres;

--
-- Name: profiles_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.profiles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.profiles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: room_members; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.room_members (
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    last_active_at timestamp(6) without time zone NOT NULL,
    room_id bigint,
    user_id bigint,
    status character varying(255) NOT NULL,
    CONSTRAINT room_members_status_check CHECK (((status)::text = ANY ((ARRAY['ONLINE'::character varying, 'OFFLINE'::character varying])::text[])))
);


ALTER TABLE public.room_members OWNER TO postgres;

--
-- Name: room_members_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.room_members ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.room_members_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: rooms; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.rooms (
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    user_id bigint,
    description character varying(255),
    title character varying(255) NOT NULL
);


ALTER TABLE public.rooms OWNER TO postgres;

--
-- Name: rooms_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.rooms ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rooms_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tasks; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tasks (
    is_completed boolean NOT NULL,
    id bigint NOT NULL,
    user_id bigint,
    title character varying(255) NOT NULL
);


ALTER TABLE public.tasks OWNER TO postgres;

--
-- Name: tasks_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tasks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tasks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    is_active boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    email character varying(255) NOT NULL,
    first_name character varying(255) NOT NULL,
    last_name character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    role character varying(255),
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['ROLE_USER'::character varying, 'ROLE_ADMIN'::character varying])::text[])))
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: favorite_rooms favorite_rooms_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.favorite_rooms
    ADD CONSTRAINT favorite_rooms_pkey PRIMARY KEY (id);


--
-- Name: favorite_rooms favorite_rooms_user_id_room_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.favorite_rooms
    ADD CONSTRAINT favorite_rooms_user_id_room_id_key UNIQUE (user_id, room_id);


--
-- Name: profiles profiles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.profiles
    ADD CONSTRAINT profiles_pkey PRIMARY KEY (id);


--
-- Name: profiles profiles_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.profiles
    ADD CONSTRAINT profiles_user_id_key UNIQUE (user_id);


--
-- Name: room_members room_members_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.room_members
    ADD CONSTRAINT room_members_pkey PRIMARY KEY (id);


--
-- Name: room_members room_members_user_id_room_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.room_members
    ADD CONSTRAINT room_members_user_id_room_id_key UNIQUE (user_id, room_id);


--
-- Name: rooms rooms_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rooms
    ADD CONSTRAINT rooms_pkey PRIMARY KEY (id);


--
-- Name: rooms rooms_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rooms
    ADD CONSTRAINT rooms_user_id_key UNIQUE (user_id);


--
-- Name: tasks tasks_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tasks
    ADD CONSTRAINT tasks_pkey PRIMARY KEY (id);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: idx_fav_room_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_fav_room_id ON public.favorite_rooms USING btree (room_id);


--
-- Name: idx_profile_user_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_profile_user_id ON public.profiles USING btree (user_id);


--
-- Name: idx_room_members_room_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_room_members_room_id ON public.room_members USING btree (room_id);


--
-- Name: idx_room_title; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_room_title ON public.rooms USING btree (title);


--
-- Name: idx_task_title; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_task_title ON public.tasks USING btree (title);


--
-- Name: idx_task_user_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_task_user_id ON public.tasks USING btree (user_id);


--
-- Name: idx_user_names; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_user_names ON public.users USING btree (first_name, last_name);


--
-- Name: room_members fk1bbl9rh6ae8v6mebaoq2ilg9g; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.room_members
    ADD CONSTRAINT fk1bbl9rh6ae8v6mebaoq2ilg9g FOREIGN KEY (room_id) REFERENCES public.rooms(id);


--
-- Name: profiles fk410q61iev7klncmpqfuo85ivh; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.profiles
    ADD CONSTRAINT fk410q61iev7klncmpqfuo85ivh FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: tasks fk6s1ob9k4ihi75xbxe2w0ylsdh; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tasks
    ADD CONSTRAINT fk6s1ob9k4ihi75xbxe2w0ylsdh FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: rooms fka84ab0lpjkgd9beja545d9ysd; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rooms
    ADD CONSTRAINT fka84ab0lpjkgd9beja545d9ysd FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: favorite_rooms fkjr59t0hlxrpkqqxcpl588ykx0; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.favorite_rooms
    ADD CONSTRAINT fkjr59t0hlxrpkqqxcpl588ykx0 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: room_members fkmcymqhedxe30d98p07eeqo3my; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.room_members
    ADD CONSTRAINT fkmcymqhedxe30d98p07eeqo3my FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: favorite_rooms fkn89cahplj3qfwqlmmalnq0r3v; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.favorite_rooms
    ADD CONSTRAINT fkn89cahplj3qfwqlmmalnq0r3v FOREIGN KEY (room_id) REFERENCES public.rooms(id);