spring.application.name=virtual-workspace

spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.url=jdbc:postgresql://db:5432/test_docker

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.properties.javax.persistence.validation.mode=none

jwt.secretkey="TYzglOT53wndCh+GbSa8pTSL7m2LexEoD29Ocj35weWtJZEcCQFVkfcW2rlK2sBWBthIjszdGzRed4nGC8JERUO5YUI62HMHW2EF1Mfe36b3V/9QAhDuUNSstWdL3PmC6SaJ1N8LNBZzJQtDj31mTM6O+kcAKSI9VIsY6yHjZq8="
jwt.refreshExpiration=604800000
jwt.tokenExpiration=36000000

spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=1
spring.flyway.user=postgres
spring.flyway.password=postgres
spring.flyway.url=jdbc:postgresql://db:5432/test_docker
spring.flyway.locations=classpath:db/migration

spring.data.redis.host=redis
spring.data.redis.port=6379
spring.cache.type=redis